[workspace]
resolver = "2"
members = [
	"core",
	"core/crates/*",
	"crates/*",
	# "crates/p2p/tunnel",
	# "crates/p2p/tunnel/utils",
	"apps/cli",
	"apps/desktop/src-tauri",
	"apps/desktop/crates/*",
	"apps/mobile/modules/sd-core/core",
	"apps/mobile/modules/sd-core/android/crate",
	"apps/mobile/modules/sd-core/ios/crate",
	"apps/server",
]

[workspace.package]
license = "AGPL-3.0-only"
edition = "2021"
repository = "https://github.com/spacedriveapp/spacedrive"

[workspace.dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", branch = "spacedrive-rspc-v1", features = [
	"specta",
	"sqlite-create-many",
	"migrations",
	"sqlite",
], default-features = false }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", branch = "spacedrive-rspc-v1", features = [
    "specta",
	"sqlite-create-many",
	"migrations",
	"sqlite",
], default-features = false }
prisma-client-rust-sdk = { git = "https://github.com/Brendonovich/prisma-client-rust", branch = "spacedrive", features = [
	"sqlite",
], default-features = false }

tracing = { git = "https://github.com/tokio-rs/tracing", rev = "29146260fb4615d271d2e899ad95a753bb42915e" } # To work with tracing-appender
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing", rev = "29146260fb4615d271d2e899ad95a753bb42915e", features = [
	"env-filter",
] } # To work with tracing-appender
tracing-appender = { git = "https://github.com/tokio-rs/tracing", rev = "29146260fb4615d271d2e899ad95a753bb42915e" } # Unreleased changes for rolling log deletion

rspc = { version = "=1.0.0-rc.5" }
rspc-tauri = { version = "=1.0.0-rc.5" }
rspc-httpz = { version = "=1.0.0-rc.5" }
specta = { version = "=2.0.0-rc.6" }
tauri-specta = { version = "2.0.0-rc.3" }

swift-rs = { version = "1.0.6" }

tokio = { version = "1.32.0" }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
serde = { version = "1.0" }
serde_json = { version = "1.0" }

[patch.crates-io]
# Proper IOS Support
if-watch = { git = "https://github.com/oscartbeaumont/if-watch.git", rev = "f804ad9b2005e4e760732a708aa95b4bfb376ddf" }

# Await release
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "ff77894c15c0af573ceac3d4970bd10600596242" }
rspc-tauri = { git = "https://github.com/oscartbeaumont/rspc", rev = "ff77894c15c0af573ceac3d4970bd10600596242" }
rspc-httpz = { git = "https://github.com/oscartbeaumont/rspc", rev = "ff77894c15c0af573ceac3d4970bd10600596242" }
