[env]
PROTOC = "/home/broken/Code/spacedrive/target/Frameworks/bin/protoc"
[target.x86_64-unknown-linux-gnu]
rustflags = ["-L", "/home/broken/Code/spacedrive/target/Frameworks/lib"]
[target.aarch64-unknown-linux-gnu]
rustflags = ["-L", "/home/broken/Code/spacedrive/target/Frameworks/lib"]
[alias]
prisma = "run -p prisma-cli --bin prisma --"
prisma-sync = "run -p prisma-cli --bin sync --"
